name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
         pwd
         ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after checkout 
        run: |
         pwd
         ls -a
      - name: simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John Wick
      - name: Log Greeting Time
        run: echo "{{steps.greet.outputs.time}}"