name: shell commands 

on: [push]

jobs:
  run-shell-command:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "Hello world from, github actions"
        - name: multiline script 
          run: |
            node -v
            python3 -v
            npm -v
        - name: Python commands
          run: |
            import platform 
            print(platform.processor())
          shell: python

  run-windows-command:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Directory powershell
        run: Get-location
      - name: Directory bash
        run: pwd
        shell: bash
